CREATE TABLE ESTOQ_ENTRADA(
    EE_ESTOQUE     VARCHAR(30) NOT NULL,
    EE_PRODUTO     VARCHAR(30) NOT NULL,
    EE_CODIGO      VARCHAR(30) NOT NULL,
    EE_QTD NUMERIC(18,2),
    EE_DATA TIMESTAMP
)
CREATE TABLE ESTOQ_SAIDA(
    ES_ESTOQUE      VARCHAR(30) NOT NULL,
    ES_PRODUTO     VARCHAR(30) NOT NULL,
    ES_CODIGO      VARCHAR(30) NOT NULL,
    ES_QTD NUMERIC(18,2),
    ES_DATA TIMESTAMP
)
