CREATE TABLE PESSOAS(
    PESS_CODIGO VARCHAR(30),
    PESS_DESCRICAO VARCHAR(100),
    PESS_TIPO CHAR,
    PESS_APELIDO VARCHAR(60),
    PESS_CONTATO VARCHAR(60),
    PESS_TELCONTATO DMTELEFONE,
    PESS_FAX DMTELEFONE,
    PESS_RAMAL INTEGER,
    PESS_CNPJ DMCNPJ,
    PESS_CPF DMCPF,
    PESS_RG VARCHAR(10),
    PESS_INSCESTADUAL DMINSCESTADUAL,
    PESS_INSCMUNICIPAL dminscmunicipal,
    PESS_EMAIL VARCHAR(60),
    PESS_DTCADASTRO DATE
)
CREATE TABLE PESSADD(
    PADD_PESSOA VARCHAR(30),
    PADD_CARGO VARCHAR(20),
    PADD_ESTCIVIL CHAR,
    PADD_NATURALIDADE VARCHAR(30),
    PADD_CONJUGUE VARCHAR(30),
    PADD_CONJTEL DMTELEFONE,
    PADD_CONJCEL DMCELULAR,
    PADD_DTNASC DATE
)

CREATE TABLE RELPESSEND(
    RPE_PESSOA VARCHAR(30),
    RPE_CODIGO VARCHAR(30),
    RPE_LOGRADOURO VARCHAR(60),
    RPE_NR VARCHAR(5),
    RPE_COMPLEMENTO VARCHAR(20),
    RPE_BAIRRO VARCHAR(20),
    RPE_TIPO CHAR,
    RPE_OBS VARCHAR(20)
)
CREATE TABLE RELPESSTEL(
    RPT_PESSOA VARCHAR(30),
    RPT_CODIGO VARCHAR(30),
    RPT_TELEFONE DMTELEFONE,
    RPT_TIPO VARCHAR(1)
)
