/******************************************************************************/
/***          Generated by IBExpert 2012.02.21 03/11/2015 21:32:38          ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES UTF8;

SET CLIENTLIB 'C:\Program Files\Firebird\Firebird_2_5\WOW64\fbclient.dll';

CREATE DATABASE 'C:\Users\Danilo de Canini\Desktop\BD\DATABASE.FDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 4096
DEFAULT CHARACTER SET UTF8 COLLATION UTF8;



SET TERM ^ ; 



/******************************************************************************/
/***                           Stored Procedures                            ***/
/******************************************************************************/

CREATE PROCEDURE SP_GEN_CENTRODECUSTO_ID
RETURNS (
    ID INTEGER)
AS
BEGIN
  SUSPEND;
END^





CREATE PROCEDURE SP_GEN_DEPARTAMENTO_ID
RETURNS (
    ID INTEGER)
AS
BEGIN
  SUSPEND;
END^





CREATE PROCEDURE SP_GEN_EMPRESA_ID
RETURNS (
    ID INTEGER)
AS
BEGIN
  SUSPEND;
END^





CREATE PROCEDURE SP_GEN_HISTORICO_ID
RETURNS (
    ID INTEGER)
AS
BEGIN
  SUSPEND;
END^





CREATE PROCEDURE SP_GEN_LANCAMENTOS_ID
RETURNS (
    ID INTEGER)
AS
BEGIN
  SUSPEND;
END^





CREATE PROCEDURE SP_GEN_PLANODECONTAS_ID
RETURNS (
    ID INTEGER)
AS
BEGIN
  SUSPEND;
END^






SET TERM ; ^



/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: CENTRODECUSTO_BI */
CREATE TRIGGER CENTRODECUSTO_BI FOR CENTRODECUSTO
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.cod_cc is null) then
    new.cod_cc = gen_id(gen_centrodecusto_id,1);
end
^

/* Trigger: DEPARTAMENTO_BI */
CREATE TRIGGER DEPARTAMENTO_BI FOR DEPARTAMENTO
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.cod_dep is null) then
    new.cod_dep = gen_id(gen_departamento_id,1);
end
^

/* Trigger: EMPRESA_BI */
CREATE TRIGGER EMPRESA_BI FOR EMPRESA
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.cod_empresa is null) then
    new.cod_empresa = gen_id(gen_empresa_id,1);
end
^

/* Trigger: HISTORICO_BI */
CREATE TRIGGER HISTORICO_BI FOR HISTORICO
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.cod_hist is null) then
    new.cod_hist = gen_id(gen_historico_id,1);
end
^

/* Trigger: LANCAMENTOS_BI */
CREATE TRIGGER LANCAMENTOS_BI FOR LANCAMENTOS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.nr_lote is null) then
    new.nr_lote = gen_id(gen_lancamentos_id,1);
end
^

/* Trigger: PLANODECONTAS_BI */
CREATE TRIGGER PLANODECONTAS_BI FOR PLANODECONTAS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.cod_conta is null) then
    new.cod_conta = gen_id(gen_planodecontas_id,1);
end
^

SET TERM ; ^



/******************************************************************************/
/***                           Stored Procedures                            ***/
/******************************************************************************/


SET TERM ^ ;

ALTER PROCEDURE SP_GEN_CENTRODECUSTO_ID
RETURNS (
    ID INTEGER)
AS
begin
  id = gen_id(gen_centrodecusto_id, 1);
  suspend;
end^


ALTER PROCEDURE SP_GEN_DEPARTAMENTO_ID
RETURNS (
    ID INTEGER)
AS
begin
  id = gen_id(gen_departamento_id, 1);
  suspend;
end^


ALTER PROCEDURE SP_GEN_EMPRESA_ID
RETURNS (
    ID INTEGER)
AS
begin
  id = gen_id(gen_empresa_id, 1);
  suspend;
end^


ALTER PROCEDURE SP_GEN_HISTORICO_ID
RETURNS (
    ID INTEGER)
AS
begin
  id = gen_id(gen_historico_id, 1);
  suspend;
end^


ALTER PROCEDURE SP_GEN_LANCAMENTOS_ID
RETURNS (
    ID INTEGER)
AS
begin
  id = gen_id(gen_lancamentos_id, 1);
  suspend;
end^


ALTER PROCEDURE SP_GEN_PLANODECONTAS_ID
RETURNS (
    ID INTEGER)
AS
begin
  id = gen_id(gen_planodecontas_id, 1);
  suspend;
end^



SET TERM ; ^
