/******************************************************************************/
/***          Generated by IBExpert 2012.02.21 03/11/2015 21:09:28          ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES UTF8;

SET CLIENTLIB 'C:\Program Files\Firebird\Firebird_2_5\WOW64\fbclient.dll';

CREATE DATABASE 'C:\Users\Danilo de Canini\Desktop\BD\DATABASE.FDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 4096
DEFAULT CHARACTER SET UTF8 COLLATION UTF8;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE HISTORICO (
    COD_HIST   INTEGER NOT NULL,
    HIST_NOME  VARCHAR(20) NOT NULL
);



/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE HISTORICO ADD CONSTRAINT PK_HISTORICO PRIMARY KEY (COD_HIST);
