/******************************************************************************/
/***          Generated by IBExpert 2012.02.21 03/11/2015 21:09:41          ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES UTF8;

SET CLIENTLIB 'C:\Program Files\Firebird\Firebird_2_5\WOW64\fbclient.dll';

CREATE DATABASE 'C:\Users\Danilo de Canini\Desktop\BD\DATABASE.FDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 4096
DEFAULT CHARACTER SET UTF8 COLLATION UTF8;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE LANCAMENTOS (
    NR_LOTE           INTEGER NOT NULL,
    NR_LANCAMENTO     INTEGER,
    DT_LANCAMENTO     DATE,
    DEBITO            INTEGER,
    CENTRODECUSTO_DB  INTEGER,
    CREDITO           INTEGER,
    CENTRODECUSTO_CR  INTEGER,
    HISTORICO         INTEGER,
    VAR_HISTORICO     VARCHAR(100),
    VALOR             INTEGER
);



/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE LANCAMENTOS ADD PRIMARY KEY (NR_LOTE);
