/******************************************************************************/
/***          Generated by IBExpert 2012.02.21 03/11/2015 21:09:54          ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES UTF8;

SET CLIENTLIB 'C:\Program Files\Firebird\Firebird_2_5\WOW64\fbclient.dll';

CREATE DATABASE 'C:\Users\Danilo de Canini\Desktop\BD\DATABASE.FDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 4096
DEFAULT CHARACTER SET UTF8 COLLATION UTF8;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE PLANODECONTAS (
    COD_CONTA   INTEGER NOT NULL,
    CONTA       INTEGER,
    DESC_CONTA  VARCHAR(20),
    ANALITICA   VARCHAR(1)
);



/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE PLANODECONTAS ADD PRIMARY KEY (COD_CONTA);
