/******************************************************************************/
/***          Generated by IBExpert 2012.02.21 02/11/2015 22:01:59          ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES UTF8;

SET CLIENTLIB 'C:\Program Files\Firebird\Firebird_2_5\WOW64\fbclient.dll';

CREATE DATABASE 'C:\Users\Danilo de Canini\Desktop\BD\DATABASE.FDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 4096
DEFAULT CHARACTER SET UTF8 COLLATION UTF8;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE CENTRODECUSTO (
    COD_CC     INTEGER NOT NULL,
    NUM_CC     INTEGER,
    DESC_CC    VARCHAR(60),
    ANALITICO  VARCHAR(1),
    COD_GRUPO  INTEGER
);

CREATE TABLE DEPARTAMENTO (
    COD_DEP       INTEGER NOT NULL,
    COD_EMPRESAR  INTEGER NOT NULL,
    DP_NOME       VARCHAR(40) NOT NULL,
    DP_DESC       VARCHAR(60) NOT NULL
);

CREATE TABLE EMPRESA (
    COD_EMPRESA   INTEGER NOT NULL,
    CNPJ_EMPRESA  NUMERIC(18,2),
    EMP_RAZAO     VARCHAR(60),
    EMP_NOMEF     VARCHAR(60),
    EMP_ENDERECO  VARCHAR(60),
    EMP_END_NUM   INTEGER,
    EMP_BAIRRO    VARCHAR(20),
    EMP_CIDADE    VARCHAR(60),
    EMP_UF        VARCHAR(2),
    EMP_CEP       INTEGER,
    EMP_FONE      INTEGER,
    EMP_TITULAR   VARCHAR(60)
);

CREATE TABLE LANCAMENTOS (
    NR_LOTE           INTEGER NOT NULL,
    NR_LANCAMENTO     INTEGER,
    DT_LANCAMENTO     DATE,
    DEBITO            INTEGER,
    CENTRODECUSTO_DB  INTEGER,
    CREDITO           INTEGER,
    CENTRODECUSTO_CR  INTEGER,
    HISTORICO         INTEGER,
    VAR_HISTORICO     VARCHAR(100),
    VALOR             INTEGER
);

CREATE TABLE PLANODECONTAS (
    COD_CONTA   INTEGER NOT NULL,
    CONTA       INTEGER,
    DESC_CONTA  VARCHAR(20),
    ANALITICA   VARCHAR(1)
);



/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE CENTRODECUSTO ADD PRIMARY KEY (COD_CC);
ALTER TABLE DEPARTAMENTO ADD CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (COD_DEP);
ALTER TABLE EMPRESA ADD PRIMARY KEY (COD_EMPRESA);
ALTER TABLE LANCAMENTOS ADD PRIMARY KEY (NR_LOTE);
ALTER TABLE PLANODECONTAS ADD PRIMARY KEY (COD_CONTA);


/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE CENTRODECUSTO ADD FOREIGN KEY (COD_GRUPO) REFERENCES EMPRESA (COD_EMPRESA);
ALTER TABLE DEPARTAMENTO ADD CONSTRAINT FK_DEPARTAMENTO_1 FOREIGN KEY (COD_EMPRESAR) REFERENCES EMPRESA (COD_EMPRESA);
