/******************************************************************************/
/***               Generated by IBExpert 22/10/2015 14:35:53                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE ESTOQ_MOVIMENTO (
    EM_EMPRESA     INTEGER NOT NULL,
    EM_PRODUTO     VARCHAR(30) NOT NULL,
    EM_BLOCO       INTEGER NOT NULL,
    EM_PRATELEIRA  INTEGER NOT NULL,
    EM_ESTOQUE     VARCHAR(30) NOT NULL,
    EM_CODIGO      VARCHAR(30) NOT NULL,
    EM_TIPO     CHAR(1),
    EM_QTD      NUMERIC(18,2),
    EM_DATA     TIMESTAMP,
    EM_OBS      VARCHAR(100),
    EM_VALOR_FINANCEIRO NUMERIC(18,2)
);




/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE ESTOQ_MOVIMENTO ADD CONSTRAINT PK_ESTOQ_MOVIMENTO PRIMARY KEY (EM_EMPRESA, EM_PRODUTO, EM_BLOCO, EM_PRATELEIRA, EM_ESTOQUE, EM_CODIGO);


/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE ESTOQ_MOVIMENTO ADD CONSTRAINT FK_EM_MOVIMENTO FOREIGN KEY (EM_EMPRESA, EM_PRODUTO, EM_BLOCO, EM_PRATELEIRA, EM_ESTOQUE) REFERENCES ESTOQUE (ESTOQ_EMPRESA, ESTOQ_PRODUTO, ESTOQ_BLOCO, ESTOQ_PRATELEIRA, ESTOQ_CODIGO);


/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/
