CREATE TABLE ESTOQ_MOVIMENTO (
    EM_EMPRESA  INTEGER NOT NULL,
    EM_ESTOQUE  VARCHAR(30) NOT NULL,
    EM_PRODUTO  VARCHAR(30) NOT NULL,
    EM_TIPO     CHAR,
    EM_CODIGO   VARCHAR(30) NOT NULL,
    EM_QTD      NUMERIC(18,2),
    EM_DATA     TIMESTAMP,
    EM_OBS      VARCHAR(100)
);



ALTER TABLE ESTOQ_MOVIMENTO ADD CONSTRAINT PK_ESTOQ_MOVIMENTO PRIMARY KEY (EM_EMPRESA, EM_ESTOQUE, EM_PRODUTO, EM_CODIGO);


ALTER TABLE ESTOQ_MOVIMENTO ADD CONSTRAINT FK_EM_MOVIMENTO FOREIGN KEY (EM_ESTOQUE, EM_PRODUTO) REFERENCES ESTOQUE (ESTOQ_CODIGO, ESTOQ_PRODUTO);

