CREATE TABLE FORNECEDOR(
    FORN_CODIGO INTEGER,
    FORN_DESCRICAO VARCHAR(100),
    FORN_LOGRADOURO VARCHAR(100),
    FORN_NR VARCHAR(10),
    FORN_BAIRRO VARCHAR(60),
    FORN_COMPLEMENTO VARCHAR(60),
    FORN_CONTATO VARCHAR(60),
    FORN_TEL1 VARCHAR(20),
    FORN_TEL2 VARCHAR(20),
    FORN_TEL3 VARCHAR(20),
    FORN_CEL VARCHAR(20)
)
