/******************************************************************************/
/***         Generated by IBExpert 2012.5.19.1 03/11/2015 20:35:47          ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES ASCII;

SET CLIENTLIB 'C:\Program Files\Firebird\Firebird_2_5\bin\fbclient.dll';

CREATE DATABASE 'C:\Users\LUCAS\Desktop\Mtek-Repository\trunk\BD\SQLS\COMERCIAL.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET ASCII COLLATION ASCII;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE ITENSCOMPRA (
    ITC_ITEMCOMPRA  INTEGER NOT NULL,
    ITC_PRODUTO     INTEGER NOT NULL,
    ITC_QUANTIDADE  NUMERIC(9,0),
    ITC_DESCONTO    NUMERIC(18,2),
    ITC_SITUACAO    VARCHAR(40)
);

CREATE TABLE NFCOMPRA (
    NF_COMPRA       INTEGER NOT NULL,
    NF_PESSOA       INTEGER NOT NULL,
    NF_DATACOMPRA   DATE,
    NF_NOMECONTATO  VARCHAR(40)
);

CREATE TABLE PEDIDOS (
    PED_PEDIDO       INTEGER NOT NULL,
    PES_PESSOA       INTEGER NOT NULL,
    PED_DATAPEDIDO   DATE,
    PED_DATACLIENTE  DATE,
    PED_VALORTOTAL   NUMERIC(18,2),
    PED_DESCONTO     NUMERIC(6,2)
);

CREATE TABLE TIPOMOVIMENTACAO (
    TIP_MOVIMENTACAO  INTEGER NOT NULL,
    TIP_DESCRICAO     VARCHAR(60)
);

