CREATE TABLE MARCAS (
    MARC_EMPRESA    INTEGER NOT NULL,
    MARC_CODIGO     INTEGER NOT NULL,
    MARC_DESCRICAO  VARCHAR(60),
    MARC_OBS        VARCHAR(100)
);


ALTER TABLE MARCAS ADD CONSTRAINT PK_MARCAS PRIMARY KEY (MARC_EMPRESA, MARC_CODIGO);

