CREATE TABLE PESSOAS (
    PESS_EMPRESA        INTEGER NOT NULL,
    PESS_CODIGO         VARCHAR(30) NOT NULL,
    PESS_DESCRICAO      VARCHAR(100),
    PESS_TIPO           CHAR(1),
    PESS_APELIDO        VARCHAR(60),
    PESS_CONTATO        VARCHAR(60),
    PESS_TELCONTATO     DMTELEFONE /* DMTELEFONE = VARCHAR(12) */,
    PESS_FAX            DMTELEFONE /* DMTELEFONE = VARCHAR(12) */,
    PESS_RAMAL          INTEGER,
    PESS_CNPJ           DMCNPJ /* DMCNPJ = VARCHAR(14) */,
    PESS_CPF            DMCPF /* DMCPF = VARCHAR(11) */,
    PESS_RG             VARCHAR(10),
    PESS_INSCESTADUAL   DMINSCESTADUAL /* DMINSCESTADUAL = VARCHAR(9) */,
    PESS_INSCMUNICIPAL  DMINSCMUNICIPAL /* DMINSCMUNICIPAL = VARCHAR(15) */,
    PESS_EMAIL          VARCHAR(60),
    PESS_DTCADASTRO     DATE
);


ALTER TABLE PESSOAS ADD CONSTRAINT PK_PESSOA PRIMARY KEY (PESS_EMPRESA, PESS_CODIGO);

