CREATE TABLE RELPRODFORN (
    RPF_EMPRESA     INTEGER NOT NULL,
    RPF_PRODUTO     VARCHAR(30) NOT NULL,
    RPF_PESSOA      VARCHAR(60) NOT NULL,
    RPF_CODREF      VARCHAR(30),
    RPF_VLRBRUTO    NUMERIC(18,2),
    RPF_PERCDESC    NUMERIC(18,2),
    RPF_VLRDESC     NUMERIC(18,2),
    RPF_VLRLIQUIDO  NUMERIC(18,2),
    RPF_DTCOMPRA    DATE,
    RPF_CONTATO     VARCHAR(20)
);


ALTER TABLE RELPRODFORN ADD CONSTRAINT PK_RELPRODFORN PRIMARY KEY (RPF_EMPRESA, RPF_PRODUTO, RPF_PESSOA);


ALTER TABLE RELPRODFORN ADD CONSTRAINT FK_RPF_PESSOA FOREIGN KEY (RPF_PESSOA) REFERENCES PESSOAS (PESS_CODIGO)
  USING INDEX FK_RELPRODFORN_PESSOA;
ALTER TABLE RELPRODFORN ADD CONSTRAINT FK_RPF_PRODUTO FOREIGN KEY (RPF_PRODUTO) REFERENCES PRODUTOS (PRO_CODIGO)
  USING INDEX FK_RELPRODFORN_PRODUTO;

