/******************************************************************************/
/***               Generated by IBExpert 10/10/2015 15:25:20                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE RELPRODFORN (
    RPF_PRODUTO     VARCHAR(30) NOT NULL,
    RPF_PESSOA      VARCHAR(60) NOT NULL,
    RPF_CODREF      VARCHAR(30),
    RPF_VLRBRUTO    NUMERIC(18,2),
    RPF_PERCDESC    NUMERIC(18,2),
    RPF_VLRDESC     NUMERIC(18,2),
    RPF_VLRLIQUIDO  NUMERIC(18,2),
    RPF_DTCOMPRA    DATE,
    RPF_CONTATO     VARCHAR(20)
);




/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE RELPRODFORN ADD CONSTRAINT PK_RELPRODFORN PRIMARY KEY (RPF_PRODUTO, RPF_PESSOA);


/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE RELPRODFORN ADD CONSTRAINT FK_RPF_PESSOA FOREIGN KEY (RPF_PESSOA) REFERENCES PESSOAS (PESS_CODIGO)
  USING INDEX FK_RELPRODFORN_PESSOA;
ALTER TABLE RELPRODFORN ADD CONSTRAINT FK_RPF_PRODUTO FOREIGN KEY (RPF_PRODUTO) REFERENCES PRODUTOS (PRO_CODIGO)
  USING INDEX FK_RELPRODFORN_PRODUTO;


/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/

