CREATE TABLE RELPESSTEL (
    RPT_EMPRESA   INTEGER NOT NULL,
    RPT_PESSOA    VARCHAR(30) NOT NULL,
    RPT_CODIGO    VARCHAR(30) NOT NULL,
    RPT_TELEFONE  DMTELEFONE /* DMTELEFONE = VARCHAR(12) */,
    RPT_TIPO      VARCHAR(1)
);


ALTER TABLE RELPESSTEL ADD CONSTRAINT PK_RELPESSTEL PRIMARY KEY (RPT_EMPRESA, RPT_PESSOA, RPT_CODIGO);


ALTER TABLE RELPESSTEL ADD CONSTRAINT FK_RPT_PESSOA FOREIGN KEY (RPT_PESSOA) REFERENCES PESSOAS (PESS_CODIGO);


