CREATE TABLE CHAMADOS (
    CHA_CODIGO        INTEGER NOT NULL,
    CHA_EMPRESA       INTEGER NOT NULL,
    CHA_DEPARTAMENTO  INTEGER NOT NULL,
    CHA_FUNCIONARIO   INTEGER NOT NULL,
    CHA_PROPRIETARIO  INTEGER NOT NULL,
    CHA_DESCRICAO     VARCHAR(100),
    CHA_PRIORIDADE    varchar(20) default 'Normal' not null,
    CHA_STATUS        varchar(15) default 'Analise' not null,
    CHA_DATA_ENTRADA  DATE not null,
    CHA_TIPO_ERRO INTEGER NOT null,
    CHA_DATA_SAIDA    DATE,
    CHA_PRODUTO_UTILIZADO INTEGER
);

CREATE TABLE PRODUTOS_UTILIZADO (
    PRU_CODIGO integer NOT NULL,
    PRU_CHAMADO integer NOT NULL,
    PRU_PRODUTO VARCHAR(20)
);

CREATE TABLE TIPOS_ERROS (
    TER_CODIGO INTEGER NOT NULL,
    TER_DESCRICAO VARCHAR(20)
);

/* CAMPOS DA TABELA TIPO DE ERRO */

alter table tipos_erros add constraint PK_TER_CODIGO primary key (TER_CODIGO);


/* CAMPOS DA TABELA PRODUTO UTILIZADO */

ALTER TABLE produtos_utilizado ADD constraint PK_PRU_CODIGO PRIMARY key (PRU_CODIGO);

ALTER TABLE produtos_utilizado ADD constraint FK_PRU_CHAMADO foreign KEY(PRU_CHAMADO) references chamados (CHA_CODIGO);

ALTER TABLE produtos_utilizado ADD constraint FK_PRU_PRODUTO foreign KEY(PRU_PRODUTO) references PRODUTOS (PRO_CODIGO);


/* CAMPOS DA TABELA CHAMADO */
ALTER TABLE CHAMADOS ADD constraint PK_CHA_CODIGO PRIMARY KEY (CHA_CODIGO);

ALTER TABLE CHAMADOS ADD CONSTRAINT FK_CHA_EMPRESA FOREIGN KEY (CHA_EMPRESA) REFERENCES EMPRESA (EMP_COD);

ALTER TABLE CHAMADOS ADD CONSTRAINT FK_CHA_DEPARTAMENTO FOREIGN KEY (CHA_EMPRESA, CHA_DEPARTAMENTO) REFERENCES DEPARTAMENTO (DEP_EMPRESAR,DEP_COD);

ALTER TABLE CHAMADOS ADD CONSTRAINT FK_CHA_FUNCIONARIO FOREIGN KEY (CHA_FUNCIONARIO) REFERENCES pessoas (PESS_CODIGO);

ALTER TABLE CHAMADOS ADD CONSTRAINT FK_CHA_PROPRIETARIO FOREIGN KEY (CHA_PROPRIETARIO) REFERENCES PESSOAS (PESS_CODIGO);

ALTER TABLE CHAMADOS ADD constraint FK_CHA_TIPO_ERRO foreign KEY (CHA_TIPO_ERRO) references tipos_erros (TER_CODIGO);


CREATE GENERATOR GEN_CHAMADO;
SET GENERATOR GEN_CHAMADO TO 1;

CREATE GENERATOR GEN_PRODUTO_UTILIZADO;
SET GENERATOR  GEN_PRODUTO_UTILIZADO TO 1;

CREATE GENERATOR GEN_TIPO_ERRO;
SET GENERATOR GEN_TIPO_ERRO TO 1;
