-- Arrumar campos de relacionamento


CREATE TABLE CHAMADOS (
    CHA_CODIGO        INTEGER NOT NULL,
    CHA_EMPRESA       INTEGER NOT NULL,
    CHA_DEPARTAMENTO  INTEGER NOT NULL,
    CHA_FUNCIONARIO   INTEGER NOT NULL,
    CHA_PROPRIETARIO  VARCHAR(60) NOT NULL,
    CHA_DESCRICAO     VARCHAR(100),
    CHA_PRIORIDADE    varchar(20) default 'Normal' not null,
    CHA_STATUS        varchar(15) default 'Analise' not null,
    CHA_DATA_ENTRADA  DATE not null,
    CHA_TIPO_ERRO VARCHAR(20) NOT null, 
    CHA_DATA_SAIDA    DATE,
    CHA_PRODUTO_UTILIZADO INTEGER NOT NULL
);

CREATE TABLE PRODUTOS_UTILIZADO (
    PRU_CODIGO integer NOT NULL,
    PRU_CHAMADO integer NOT NULL,
    PRU_PRODUTO VARCHAR(20)
);

CREATE TABLE TIPOS_ERROS (
    TER_CODIGO VARCHAR(1) primary KEY NOT NULL,
    TER_DESCRICAO VARCHAR(20)
);


/* CAMPOS DA TABELA TIPOS DE ERRO */

ALTER TABLE tipos_erros ADD primary key (TER_CODIGO)

/* CAMPOS DA TABELA PRODUTO UTILIZADO */

ALTER TABLE produtos_utilizado ADD PRIMARY key (PRU_CODIGO);

ALTER TABLE produtos_utilizado ADD constraint FK_PRU_CHAMADO foreign KEY(PRU_CHAMADO) references chamados (CHA_CODIGO);

ALTER TABLE produtos_utilizado ADD constraint FK_PRU_PRODUTO foreign KEY(PRU_PRODUTO) references PRODUTOS (PRO_CODIGO);


/* CAMPOS DA TABELA CHAMADO */
ALTER TABLE CHAMADOS ADD PRIMARY KEY (CHA_CODIGO);

ALTER TABLE CHAMADOS ADD CONSTRAINT FK_CHA_EMPRESA FOREIGN KEY (CHA_EMPRESA) REFERENCES EMPRESA (COD_EMPRESA);

ALTER TABLE CHAMADOS ADD CONSTRAINT FK_CHA_DEPARTAMENTO FOREIGN KEY (CHA_DEPARTAMENTO) REFERENCES departamento (COD_DEP);

ALTER TABLE CHAMADOS ADD CONSTRAINT FK_CHA_FUNCIONARIO FOREIGN KEY (CHA_FUNCIONARIO) REFERENCES pessoas (PESS_CODIGO);

ALTER TABLE CHAMADOS ADD CONSTRAINT FK_CHA_PROPRIETARIO FOREIGN KEY (CHA_PROPRIETARIO) REFERENCES PESSOAS (PESS_CODIGO);

ALTER TABLE CHAMADOS ADD constraint FK_CHA_TIPO_ERRO foreign KEY (CHA_TIPO_ERRO) references tipos_erros (TER_CODIGO);
