/******************************************************************************/
/***          Generated by IBExpert 2012.02.21 11/11/2015 02:34:13          ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES UTF8;

SET CLIENTLIB 'C:\Windows\System32\FBCLIENT.DLL';

CREATE DATABASE 'C:\Users\valeria\Desktop\fluxocaixa\FLUXOCAIXA.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 4096
DEFAULT CHARACTER SET UTF8 COLLATION UTF8;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE CONTROLECAIXA (
    CX_CODEMPRESA     INTEGER NOT NULL,
    CX_CODLANCAMENTO  INTEGER NOT NULL,
    CX_SALDOANTERIOR  NUMERIC(18,2),
    CX_DT_ABERTURA    DATE,
    CX_HR_ABERTURA    TIME,
    CX_TOTALRECEBER   NUMERIC(18,2),
    CX_TOTALPAGA      NUMERIC(18,2),
    CX_DT_FECHAMENTO  DATE,
    CX_HR_FECHAMENTO  TIME,
    CX_SALDOTOTAL     NUMERIC(18,2),
    CX_SITUACAO       VARCHAR(1)
);

CREATE TABLE MOVCAIXA (
    MCX_CODEMPRESA    INTEGER NOT NULL,
    MCX_CODMOV        INTEGER NOT NULL,
    MCX_DATAMOV       DATE,
    MCX_TIPOMOV       VARCHAR(1),
    MCX_HISTORICOMOV  VARCHAR(60),
    MCX_VALORMOV      NUMERIC(18,2)
);



/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE CONTROLECAIXA ADD CONSTRAINT PK_CONTROLECAIXA PRIMARY KEY (CX_CODEMPRESA, CX_CODLANCAMENTO);
ALTER TABLE MOVCAIXA ADD CONSTRAINT PK_MOVCAIXA PRIMARY KEY (MCX_CODEMPRESA, MCX_CODMOV);


/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE CONTROLECAIXA ADD CONSTRAINT PK_CX_EMPRESA FOREIGN KEY (CX_CODEMPRESA) REFERENCES EMPRESA (EMP_COD);
ALTER TABLE MOVCAIXA ADD CONSTRAINT FK_MOVCAIXA_EMPRESA FOREIGN KEY (MCX_CODEMPRESA) REFERENCES EMPRESA (EMP_COD);
